### ISSUE TITLE
好的谢谢

### ISSUE THREAD

**Issue by WeiLaiF** [UlyssesZh/yt-dlp-danmaku#1]

**Comment by UlyssesZh** [comment]
感谢分享. 几个要点:
- 你的发的文件是仅包含了一个 exe 文件的压缩文件. 因为你不知道是谁编写的, 也并不持有它的源代码, 你不能信任这个软件, 在用户机器上运行它会有风险. 所以请不要公开这样的软件.
- 我不用 Windows, 所以我没法测试你发的文件.
- 因为你没有它的源代码, 这个软件对我没有任何参考价值.
